/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MerchantIndexRouteImport } from './routes/merchant.index'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as PayTxnRouteImport } from './routes/pay.$txn'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as MerchantOrdersRouteImport } from './routes/merchant.orders'
import { Route as MerchantMenuRouteImport } from './routes/merchant.menu'
import { Route as ApiPublicPhonepeCallbackRouteImport } from './routes/api.public.phonepe-callback'

const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MerchantRoute,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PayTxnRoute = PayTxnRouteImport.update({
  id: '/pay/$txn',
  path: '/pay/$txn',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantOrdersRoute = MerchantOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantMenuRoute = MerchantMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => MerchantRoute,
} as any)
const ApiPublicPhonepeCallbackRoute =
  ApiPublicPhonepeCallbackRouteImport.update({
    id: '/api/public/phonepe-callback',
    path: '/api/public/phonepe-callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/explore': typeof ExploreRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/merchant/menu': typeof MerchantMenuRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/order/$id': typeof OrderIdRoute
  '/pay/$txn': typeof PayTxnRoute
  '/r/$slug': typeof RSlugRoute
  '/merchant/': typeof MerchantIndexRoute
  '/api/public/phonepe-callback': typeof ApiPublicPhonepeCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/explore': typeof ExploreRoute
  '/merchant/menu': typeof MerchantMenuRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/order/$id': typeof OrderIdRoute
  '/pay/$txn': typeof PayTxnRoute
  '/r/$slug': typeof RSlugRoute
  '/merchant': typeof MerchantIndexRoute
  '/api/public/phonepe-callback': typeof ApiPublicPhonepeCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/explore': typeof ExploreRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/merchant/menu': typeof MerchantMenuRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/order/$id': typeof OrderIdRoute
  '/pay/$txn': typeof PayTxnRoute
  '/r/$slug': typeof RSlugRoute
  '/merchant/': typeof MerchantIndexRoute
  '/api/public/phonepe-callback': typeof ApiPublicPhonepeCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/checkout'
    | '/explore'
    | '/merchant'
    | '/merchant/menu'
    | '/merchant/orders'
    | '/order/$id'
    | '/pay/$txn'
    | '/r/$slug'
    | '/merchant/'
    | '/api/public/phonepe-callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/checkout'
    | '/explore'
    | '/merchant/menu'
    | '/merchant/orders'
    | '/order/$id'
    | '/pay/$txn'
    | '/r/$slug'
    | '/merchant'
    | '/api/public/phonepe-callback'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/checkout'
    | '/explore'
    | '/merchant'
    | '/merchant/menu'
    | '/merchant/orders'
    | '/order/$id'
    | '/pay/$txn'
    | '/r/$slug'
    | '/merchant/'
    | '/api/public/phonepe-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  ExploreRoute: typeof ExploreRoute
  MerchantRoute: typeof MerchantRouteWithChildren
  OrderIdRoute: typeof OrderIdRoute
  PayTxnRoute: typeof PayTxnRoute
  RSlugRoute: typeof RSlugRoute
  ApiPublicPhonepeCallbackRoute: typeof ApiPublicPhonepeCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$txn': {
      id: '/pay/$txn'
      path: '/pay/$txn'
      fullPath: '/pay/$txn'
      preLoaderRoute: typeof PayTxnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/orders': {
      id: '/merchant/orders'
      path: '/orders'
      fullPath: '/merchant/orders'
      preLoaderRoute: typeof MerchantOrdersRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/menu': {
      id: '/merchant/menu'
      path: '/menu'
      fullPath: '/merchant/menu'
      preLoaderRoute: typeof MerchantMenuRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/api/public/phonepe-callback': {
      id: '/api/public/phonepe-callback'
      path: '/api/public/phonepe-callback'
      fullPath: '/api/public/phonepe-callback'
      preLoaderRoute: typeof ApiPublicPhonepeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MerchantRouteChildren {
  MerchantMenuRoute: typeof MerchantMenuRoute
  MerchantOrdersRoute: typeof MerchantOrdersRoute
  MerchantIndexRoute: typeof MerchantIndexRoute
}

const MerchantRouteChildren: MerchantRouteChildren = {
  MerchantMenuRoute: MerchantMenuRoute,
  MerchantOrdersRoute: MerchantOrdersRoute,
  MerchantIndexRoute: MerchantIndexRoute,
}

const MerchantRouteWithChildren = MerchantRoute._addFileChildren(
  MerchantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  ExploreRoute: ExploreRoute,
  MerchantRoute: MerchantRouteWithChildren,
  OrderIdRoute: OrderIdRoute,
  PayTxnRoute: PayTxnRoute,
  RSlugRoute: RSlugRoute,
  ApiPublicPhonepeCallbackRoute: ApiPublicPhonepeCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
