/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BecomeMerchantRouteImport } from './routes/become-merchant'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MerchantIndexRouteImport } from './routes/merchant.index'
import { Route as PayTxnRouteImport } from './routes/pay.$txn'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as MerchantOrdersRouteImport } from './routes/merchant.orders'
import { Route as MerchantMenuRouteImport } from './routes/merchant.menu'

const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeMerchantRoute = BecomeMerchantRouteImport.update({
  id: '/become-merchant',
  path: '/become-merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MerchantRoute,
} as any)
const PayTxnRoute = PayTxnRouteImport.update({
  id: '/pay/$txn',
  path: '/pay/$txn',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantOrdersRoute = MerchantOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantMenuRoute = MerchantMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => MerchantRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/become-merchant': typeof BecomeMerchantRoute
  '/checkout': typeof CheckoutRoute
  '/menu': typeof MenuRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/orders': typeof OrdersRoute
  '/merchant/menu': typeof MerchantMenuRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/order/$id': typeof OrderIdRoute
  '/pay/$txn': typeof PayTxnRoute
  '/merchant/': typeof MerchantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/become-merchant': typeof BecomeMerchantRoute
  '/checkout': typeof CheckoutRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/merchant/menu': typeof MerchantMenuRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/order/$id': typeof OrderIdRoute
  '/pay/$txn': typeof PayTxnRoute
  '/merchant': typeof MerchantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/become-merchant': typeof BecomeMerchantRoute
  '/checkout': typeof CheckoutRoute
  '/menu': typeof MenuRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/orders': typeof OrdersRoute
  '/merchant/menu': typeof MerchantMenuRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/order/$id': typeof OrderIdRoute
  '/pay/$txn': typeof PayTxnRoute
  '/merchant/': typeof MerchantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/become-merchant'
    | '/checkout'
    | '/menu'
    | '/merchant'
    | '/orders'
    | '/merchant/menu'
    | '/merchant/orders'
    | '/order/$id'
    | '/pay/$txn'
    | '/merchant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/become-merchant'
    | '/checkout'
    | '/menu'
    | '/orders'
    | '/merchant/menu'
    | '/merchant/orders'
    | '/order/$id'
    | '/pay/$txn'
    | '/merchant'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/become-merchant'
    | '/checkout'
    | '/menu'
    | '/merchant'
    | '/orders'
    | '/merchant/menu'
    | '/merchant/orders'
    | '/order/$id'
    | '/pay/$txn'
    | '/merchant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BecomeMerchantRoute: typeof BecomeMerchantRoute
  CheckoutRoute: typeof CheckoutRoute
  MenuRoute: typeof MenuRoute
  MerchantRoute: typeof MerchantRouteWithChildren
  OrdersRoute: typeof OrdersRoute
  OrderIdRoute: typeof OrderIdRoute
  PayTxnRoute: typeof PayTxnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-merchant': {
      id: '/become-merchant'
      path: '/become-merchant'
      fullPath: '/become-merchant'
      preLoaderRoute: typeof BecomeMerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/pay/$txn': {
      id: '/pay/$txn'
      path: '/pay/$txn'
      fullPath: '/pay/$txn'
      preLoaderRoute: typeof PayTxnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/orders': {
      id: '/merchant/orders'
      path: '/orders'
      fullPath: '/merchant/orders'
      preLoaderRoute: typeof MerchantOrdersRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/menu': {
      id: '/merchant/menu'
      path: '/menu'
      fullPath: '/merchant/menu'
      preLoaderRoute: typeof MerchantMenuRouteImport
      parentRoute: typeof MerchantRoute
    }
  }
}

interface MerchantRouteChildren {
  MerchantMenuRoute: typeof MerchantMenuRoute
  MerchantOrdersRoute: typeof MerchantOrdersRoute
  MerchantIndexRoute: typeof MerchantIndexRoute
}

const MerchantRouteChildren: MerchantRouteChildren = {
  MerchantMenuRoute: MerchantMenuRoute,
  MerchantOrdersRoute: MerchantOrdersRoute,
  MerchantIndexRoute: MerchantIndexRoute,
}

const MerchantRouteWithChildren = MerchantRoute._addFileChildren(
  MerchantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BecomeMerchantRoute: BecomeMerchantRoute,
  CheckoutRoute: CheckoutRoute,
  MenuRoute: MenuRoute,
  MerchantRoute: MerchantRouteWithChildren,
  OrdersRoute: OrdersRoute,
  OrderIdRoute: OrderIdRoute,
  PayTxnRoute: PayTxnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
